# This is a basic workflow to help you get started with Actions

name: Static Analysis

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  static-analysis-flutter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Set up Flutter.
      - name: Clone Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
          cache: true
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - run: flutter analyze
        working-directory: ./app
