# This is a basic workflow to help you get started with Actions

name: Unit Test Flutter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit-tests-flutter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Set up Flutter.
      - name: Clone Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
          cache: true

      # Checkout the repository code.
      - name: Checkout
        uses: actions/checkout@v2

      # Generate unit tests coverage.
      - run: flutter test --coverage
        working-directory: ./app

      # Upload coverage.
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
